name: Android CI
on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # DO NOT add "cache: gradle" here. It is what triggers the v2 error.

    - name: Install Dependencies
      run: npm install
      working-directory: telon-gateway-app

    - name: Build APK
      run: |
        cd telon-gateway-app/android
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Telon-App
        path: telon-gateway-app/android/app/build/outputs/apk/debug/*.apk
        find . -name "*.apk" -type f -exec mv {} outputs/ \;

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: telon-app-debug
        path: outputs/
        

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: my_outputs/
